### ISSUE TITLE
Toaster not working with SSR

### ISSUE THREAD

**Issue by jonaswindey** [palantir/blueprint#1205]
### Bug report

- __Package version(s)__: 1.18.0
- __Browser and OS versions__: Chrome & OS X

#### Steps to reproduce

1. Create a Toaster instance as described in docs:

```js
import { Position, Toaster } from '@blueprintjs/core'

export const Toast = Toaster.create({
  className: 'my-toaster',
  position: Position.BOTTOM_RIGHT
})
```
2. Reference the component in your app by importing it
3. Call the show() method
```js
const key = Toast.show({ message: 'Toasted!' })
Toast.update(key, { message: 'Still toasted!' })
```

#### Actual behavior

```
ReferenceError: document is not defined
    at Function.Toaster.create (/Users/jonas/Development/3nit/zumex-v2/node_modules/@blueprintjs/core/dist/components/src/components/toast/toaster.tsx:95:61)
    at Object.<anonymous> (/Users/jonas/Development/3nit/zumex-v2/.next/dist/utils/toaster.js:10:43)
    at Module._compile (module.js:570:32)
    at loader (/Users/jonas/Development/3nit/zumex-v2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jonas/Development/3nit/zumex-v2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jonas/Development/3nit/zumex-v2/.next/dist/pages/admin/products.js:91:16)
    at Module._compile (module.js:570:32)
    at loader (/Users/jonas/Development/3nit/zumex-v2/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jonas/Development/3nit/zumex-v2/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

#### Expected behavior

Toaster shouldn't be rendered on server-side since document object doesn't exist there.

Probably additional checks are needed at https://github.com/palantir/blueprint/blob/master/packages/core/src/components/toast/toaster.tsx#L95

**Comment by jonaswindey** [comment]
Solution:

in Toaster.js, add extra check:

```js
export const Toast = (typeof window !== 'undefined')
   ? Toaster.create({
     className: 'my-toaster',
     position: Position.BOTTOM_RIGHT
   })
  : null
```

**Comment by adidahiya** [comment]
Just came across this again. It should be sufficient to conditionally create the toaster if `document` is defined. Closing as won't fix
