### ISSUE TITLE
Issues with Install via Gulp

### ISSUE THREAD

**Issue by lycovian** [palantir/blueprint#132]
Getting an error after installing master and running `npm run gulp` on my OS X box: 
```
$ git describe --tags
release-1.0.1-14-g6571359
 ~/build/blueprint  ⑂ master  »
$ npm run gulp

> blueprint@1.0.1 gulp build/blueprint
> gulp

/Users/mwilson/build/blueprint/gulp/index.js:28
        dest(project, ...paths) {
                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (build/blueprint/gulpfile.js:71:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/5.10.1/bin/node" "/usr/local/bin/npm" "run" "gulp"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! blueprint@1.0.1 gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blueprint@1.0.1 gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blueprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blueprint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blueprint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     build/blueprint/npm-debug.log
```

[npm-debug.log.zip](https://github.com/palantir/blueprint/files/587941/npm-debug.log.zip)

**Comment by giladgray** [comment]
you are not using node 6+ my friend! gotta be on a recent enough version to support some ES6 syntax.

> **Prerequisite:** Node.js v6 or v7
https://github.com/palantir/blueprint#development
