### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by mehdy** [palantir/blueprint#218]
### Bug Report

- __Package version(s)__: 1.0.1

#### Describe the issue:

as I'm trying to use blueprintjs very basically I get this error while running it:
```
/path/to/node_modules/dom4/build/dom4.max.js:760
}(window));(function (global){'use strict';
  ^

ReferenceError: window is not defined
    at Object.<anonymous> (/path/to/node_modules/dom4/build/dom4.max.js:760:3)
    at Module._compile (module.js:573:32)
    at Module._extensions..js (module.js:582:10)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Module._load (module.js:441:3)
    at Function.module._load (/path/to/node_modules/piping/lib/piping.js:218:16)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```
how I used it:
```javascript
import {
      Menu,
      MenuItem,
} from '@blueprintjs/core';

export default class App extends Component {
  render() {
    return (
      <Menu>
        <MenuItem text="New" />
      </Menu>
    );
  }
}
```
and I use [this boilerplate](https://github.com/erikras/react-redux-universal-hot-example) for my project.
#### Expected behavior:
works properly :)

**Comment by giladgray** [comment]
i'll bet you're trying to render on the server, an environment that does not provide the browser global `window`. Blueprint does not currently work OOTB in server-side rendering. Please follow #131 for the ongoing conversation.
