### ISSUE TITLE
Error: Debug Failure. False expression: <empty>

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#348]
I get a TypeScript compiler error with `@blueprintjs/core@1.3.1`: 

    Error: Debug Failure. False expression: <empty>

This does not happen with `@blueprintjs/core@1.2.0` .

### Bug report

- __Package version(s)__: `typescript@2.1.4`,  `@blueprintjs/core@1.3.1`:
- __Browser and OS versions__: Windows 10

#### Steps to reproduce

1. For example, this is file `TsBlueprintBug.ts` (just the one import line):

```
import {Dialog} from "@blueprintjs/core";
```

2. This is my `tsconfig.json`:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "jsx": "react",
    "outDir": "app",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "inlineSources": true,
    "sourceMap": true,
    "sourceRoot": "src",
    "rootDir": "src",
    "types": [
      "node",
      "mocha",
      "chai"
    ]
  }
}
```

3. compile above file with `tsc` of `typescript@2.1.4` and  `@blueprintjs/core@1.3.1` dependency.

#### Actual behavior

I get a compiler error:

```
> tsc

... WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:1794
                throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);
                ^

Error: Debug Failure. False expression:
    at Object.assert (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:1794:23)
    at resolveExternalModule (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:20568:30)
    at resolveExternalModuleNameWorker (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:20535:20)
    at mergeModuleAugmentation (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:19892:34)
    at initializeTypeChecker (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:35233:25)
    at Object.createTypeChecker (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:19739:9)
    at getDiagnosticsProducingTypeChecker (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:49608:93)
    at Object.getGlobalDiagnostics (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:49885:41)
    at compileProgram (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:51966:78)
    at compile (C:\Users\norma\WebstormProjects\cate-desktop\node_modules\typescript\lib\tsc.js:51925:26)
```

#### Expected behavior

it("should compile").

**Comment by Ciantic** [comment]
Getting same, reported to TypeScript also https://github.com/Microsoft/TypeScript/issues/10522

**Comment by Ciantic** [comment]
Btw, here is a cloneable gist to try this out:

https://gist.github.com/Ciantic/60e9dbe330922cfc41086e255820df62

It should be priority to be fixed. I've spent few hours wondering why the thing I worked on last week does not work anymore.

It fails with typescript@next and typescript@2.1.4

**Comment by Ciantic** [comment]
Here is the answer to blueprint blues today:

> seems that the problem is that @blueprintjs/core augments tether, but does not have a dependency on @types/tether in package.json.
> 
> Installing the @types/tether should avoid this error. but really the fix should be in @blueprintjs/core package.json.

So devs must add that package. See https://github.com/Microsoft/TypeScript/issues/10522

**Comment by adidahiya** [comment]
Interesting... thanks for doing that debugging @Ciantic. A missing dependency on `@types/tether` also came up here: https://github.com/palantir/blueprint/issues/201#issuecomment-266202824. I generally agree that we should add that as a `dependency` in package.json despite that fact that it will be superfluous for JS-only consumers.

**Comment by adidahiya** [comment]
`@types/tether` was added as a dependency in #360.

**Comment by codebling** [comment]
@adidahiya only [`@types/dom4` was added](https://github.com/palantir/blueprint/pull/360/commits/e9c89e06c3823db1aef1580bc47d3d518a12cdef#diff-f4f412caa68d8fde92b3d6bd3c2b3be1R9) in 360, and only to `core`. 

Haven't been following the whole discussion but [`@types/tether` has been around for a while](https://github.com/palantir/blueprint/blame/master/package.json#L31).

**Comment by adidahiya** [comment]
whoops, you're right. `@types/tether` is a dependency for this monorepo, but no in core. still needs to be added.

**Comment by llorca** [comment]
Seems super straightforward, let's do it for 1.4.0 this week in addition to the SSR stuff

**Comment by forman** [comment]
Thanks!
