### ISSUE TITLE
Yarn verify - failing tests

### ISSUE THREAD

**Issue by Jarvvski** [palantir/blueprint#3660]
#### Environment

- __Package version(s)__:  node: v8.16.0 | yarn: 1.16.0
- __Browser and OS versions__: HeadlessChrome 75.0.3770  | macOS 10.14.5 (18F203) 

#### Steps to reproduce

1. Fork repo
2. Clone to local
3. `yarn install`
4. `yarn verify`

#### Actual behavior

Failing on the karma tests on default develop branch

```sh
FAILED TESTS:
  scrollUtils
    measureScrollBarThickness
      ✖ measures correctly when only vertical scrollbar is showing
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: measures vertical scrollbar correctly: expected 0 to be above 0
          at Context.<anonymous> (test/index.js:156445:74)

      ✖ measures correctly when only horizontal scrollbar is showing
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: measures horizontal scrollbar correctly: expected 0 to be above 0
          at Context.<anonymous> (test/index.js:156451:78)

      ✖ measures correctly when both scrollbars are showing
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: measures vertical scrollbar correctly: expected 0 to be above 0
          at Context.<anonymous> (test/index.js:156455:74)

  TableQuadrantStack
    Scroll syncing
      ✖ syncs quadrant scroll offsets when scrolling the main quadrant
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: expected 1 to equal 2
          at assertScrollPositionEquals (test/index.js:158620:50)
          at Context.<anonymous> (test/index.js:158577:13)

      ✖ syncs quadrant scroll offsets when mouse-wheeling in the main quadrant
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: expected 1 to equal 2
          at assertScrollPositionEquals (test/index.js:158620:50)
          at Context.<anonymous> (test/index.js:158586:13)

      ✖ syncs quadrant scroll offsets when mouse-wheeling in the top quadrant
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: expected 1 to equal 2
          at assertScrollPositionEquals (test/index.js:158620:50)
          at Context.<anonymous> (test/index.js:158596:13)

      ✖ syncs quadrant scroll offsets when mouse-wheeling in the left quadrant
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: expected 1 to equal 2
          at assertScrollPositionEquals (test/index.js:158620:50)
          at Context.<anonymous> (test/index.js:158606:13)

      ✖ syncs quadrant scroll offsets when mouse-wheeling in the top-left quadrant
        HeadlessChrome 75.0.3770 (Mac OS X 10.14.5)
      AssertionError: expected 1 to equal 2
          at assertScrollPositionEquals (test/index.js:158620:50)
          at Context.<anonymous> (test/index.js:158615:13)
```

#### Expected behavior

Everything to run swimmingly

#### Possible solution

I'm unsure if there is a specific branch that I should be building from locally. Following the [docs](https://github.com/palantir/blueprint/blob/develop/CONTRIBUTING.md) I can't see a specific branch mentioned.

I'm following the specific node & yarn versions, so I'm not sure why that would be an issue.

**Comment by adidahiya** [comment]
Yeah I've noticed these failing locally for me as well, haven't had time to go and debug... but they seem to pass fine in the CI environment.

**Comment by Jarvvski** [comment]
Alright, I'll just set the specific tests to skip for my local env and just not include those changes in any future PR if I make one
