### ISSUE TITLE
Unable to `yarn install` when only python3 is installed

### ISSUE THREAD

**Issue by lonelyevil** [palantir/blueprint#4273]
#### Environment

- __Package version(s)__: last commit of develop branch
- __Operating System__: Archlinux
- __Browser name and version__: It doesn't matter with browser
- `python -V`: Python 3.8.5

#### Steps to reproduce

1. `yarn install`

#### Actual behavior

all unnecessary info is omitted.

```
error /mnt/hd1g/dev/blueprint/node_modules/tree-sitter-typescript: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /mnt/hd1g/dev/blueprint/node_modules/tree-sitter-typescript
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:443:11)
gyp ERR! stack     at Socket.emit (events.js:315:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:674:12)
gyp ERR! System Linux 5.7.12-arch1-1
gyp ERR! command "/usr/bin/node" "/mnt/hd1g/dev/blueprint/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/hd1g/dev/blueprint/node_modules/tree-sitter-typescript

```

#### Expected behavior

Correctly install all deps.

#### Possible solution

1. Install python2 (I am using it currently, although actually all other softwares don't depends it.)
2. Make `tree-sitter-typescript` not using the `node-gyp` depended by `node-sass`. (I am not sure if it is possible as I am not familiar with the build system.)
3. Ask `node-sass` developers to upgrade the dependency version.

Thanks!

**Comment by adidahiya** [comment]
We're using the latest version of tree-sitter-typescript, so you might want to bring this issue up with them. I guess we haven't hit this issue before because most of our dev usage is on Mac, which has Python2 installed.

**Comment by lonelyevil** [comment]
> We're using the latest version of tree-sitter-typescript, so you might want to bring this issue up with them. I guess we haven't hit this issue before because most of our dev usage is on Mac, which has Python2 installed.

I thought it maybe some problem with the build system preset or yarn related. I got almost the same error for another dep with the same command.

Complete output:
```
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning better-handlebars@0.1.1: The engine "atom" appears to be invalid.
warning language-less@0.34.3: The engine "atom" appears to be invalid.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > stylelint-config-palantir@5.0.0" has unmet peer dependency "stylelint@^13.3.2".
warning "stylelint-config-palantir > stylelint-config-standard@20.0.0" has unmet peer dependency "stylelint@>=10.1.0".
warning "stylelint-config-palantir > stylelint-order@4.0.0" has unmet peer dependency "stylelint@^10.0.1 || ^11.0.0 || ^12.0.0 || ^13.0.0".
warning " > stylelint-scss@3.18.0" has unmet peer dependency "stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0".
warning "stylelint-config-palantir > stylelint-config-standard > stylelint-config-recommended@3.0.0" has unmet peer dependency "stylelint@>=10.1.0".
warning " > @blueprintjs/core@3.30.1" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/core@3.30.1" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/datetime@3.18.5" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/datetime@3.18.5" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/docs-theme@3.6.4" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/docs-theme@3.6.4" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/select@3.13.6" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/select@3.13.6" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/table@3.8.12" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/table@3.8.12" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/test-commons@0.10.4" has unmet peer dependency "react@>=15.3.0".
warning " > @blueprintjs/timezone@3.6.10" has unmet peer dependency "react@^15.3.0 || 16".
warning " > @blueprintjs/timezone@3.6.10" has unmet peer dependency "react-dom@^15.3.0 || 16".
warning " > @blueprintjs/tslint-config@3.0.1" has unmet peer dependency "tslint@^6.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/core > sass-inline-svg@1.2.3" has unmet peer dependency "node-sass@^4.5.3".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/core > webpack-cli@3.3.12" has unmet peer dependency "webpack@4.x.x".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/docs-app > copy-webpack-plugin@6.0.3" has unmet peer dependency "webpack@^4.37.0 || ^5.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/docs-app > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/eslint-config > @typescript-eslint/eslint-plugin-tslint@3.8.0" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/karma-build-scripts > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/karma-build-scripts > karma-webpack@4.0.2" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.1" has incorrect peer dependency "react@^15.5.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.1" has unmet peer dependency "react-dom@^15.5.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.1" has unmet peer dependency "react-test-renderer@^15.5.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/test-commons > enzyme-adapter-react-16@1.15.2" has unmet peer dependency "react-dom@^16.0.0-0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/tslint-config > tslint-react@5.0.0" has unmet peer dependency "tslint@^6.0.0".
warning "workspace-aggregator-0900d857-b65f-4edb-bec3-91e95338d83a > @blueprintjs/docs-app > webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
[5/5] Building fresh packages...
[1/7] ⠄ node-sass
[7/7] ⠄ tree-sitter-typescript
[-/7] ⠄ waiting...
[6/7] ⠄ oniguruma
error /mnt/hd1g/dev/blueprint/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /mnt/hd1g/dev/blueprint/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.18.3 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:303:12)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:443:11)
gyp ERR! stack     at Socket.emit (events.js:315:20)
gyp ERR! stack     at Pipe.<anonymous> (net.js:674:12)
gyp ERR! System Linux 5.7.12-arch1-1
gyp ERR! command "/usr/bin/node" "/mnt/hd1g/dev/blueprint/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /mnt/hd1g/dev/blueprint/node_modules/oniguruma
```

**Comment by lonelyevil** [comment]
~~Found a possible solution:
add `node-gyp@7.0.0` to `node-build-scripts`, and all `yarn install` fresh build passed successfully. (any version supports python3 should be okay, I just choose the lastest version)~~

Update:
But when running test, the tests related to `@blueprintjs/timezone` is not passed. (I think it doesnt matter with newer version of `node-gyp`). Maybe it is not a correct solution.
