### ISSUE TITLE
Click inside popover content duing test

### ISSUE THREAD

**Issue by codeasashu** [palantir/blueprint#4769]
#### Environment

- __Package version(s)__:  `@blueprintjs/core": "^3.40.0", "@blueprintjs/popover2": "^0.3.1"`

- __Browser and OS versions__: `"jest": "^26.6.3", @testing-library/jest-dom": "^5.11.10"`

#### Question

I am trying to render a content inside Popover2, which have some buttons. Those buttons tiggers the handler attached to parent node. I am trying to assert that the trigger is correctly triggering the handler. I am clueless how to do it.

Here is my best attempt so far:

```js
// main.js

import SomeComponent from './some-component.js';
export default ({handleOnClick, ...props}) => {
  return (<Popover2
      content={<SomeComponent handleClick={handleOnClick} />}
      usePortal={false} placement="right">
        <span className="mytarget">Some Text</span>
  </Popover2>);
}
```

```js
// some-component.js

import React from "react";

class SomeComponent extends React.PureComponent {
   render() {
    const { handleClick } = this.props;
    return (<button onClick={handleClick}>Click Me!</button>);
  }
}

export default SomeComponent;
```

Now, I am testing this like:

```js
// __tests__/main.test.js

import React from 'react';
import {Popover2, Classes} from '@blueprintjs/popover2';
import {mount} from 'enzyme';
import {act, within, fireEvent} from '../../../test-utils';
import Main from "./main";

it('Responds to click', async () => {
    const clickHandler = jest.fn();
    const wrapper = mount(<Main handleOnClick={clickHandler} />);
    
    // Triggering popover open
    await act(async () => {
      wrapper.find('.mytarget').simulate('click');
    });

     // Now we have it open, find the button in the content, click it
     // BUT, Where is the content?
     wrapper.find('button').filter('.clickit').simulate('click'); // Error!!, no matching element found

    // Tried to use the element reference as well
    const instance = wrapper.find(Popover2).instance();
    const popoverElement = instance.popoverElement;
    const contentButton = within(popoverElement).getByText(/Click Me/i);
    fireEvent.click(contentButton); // Does nothing!!!
});
```
PS: I've already gone through [this](https://github.com/palantir/blueprint/blob/develop/packages/popover2/test/popover2Tests.tsx) but no tests were written that is interacting inside the popup container. Correct me if I am wrong!!

**Comment by codeasashu** [comment]
I've made some progress.

I think the `act` was causing all the issue. Without it, everything seems to be working fine. This is a working example:


```js
// __tests__/main.test.js

import React from 'react';
import {Popover2, Classes} from '@blueprintjs/popover2';
import {mount} from 'enzyme';
import Main from "./main";

it('Responds to click', async () => {
    const clickHandler = jest.fn();
    const wrapper = mount(<Main handleOnClick={clickHandler} />);
    
    // Trigger a click
    const targetNode = wrapper.find(`.${Classes.POPOVER2_TARGET}`);
    targetNode.simulate('click');

    // Assert popup is opened
    expect(targetNode.getDOMNode()).toHaveClass(Classes.POPOVER2_OPEN);

    // Find the target
    wrapper.find(Popover2).find('.clickit').simulate('click');

    // Assert click is triggered
    expect(clickHandler).toHaveBeenCalled();
});
```

But, removing `act` is showing this warning even though tests are passing:

```
    console.error
      Warning: An update to Popper inside a test was not wrapped in act(...).

      When testing, code that causes React state updates should be wrapped into act(...):

      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */

      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in Popper (created by Blueprint3.Popover2)
          in Manager (created by Blueprint3.Popover2)
          in Blueprint3.Popover2 (created by SchemaDropdown)
          in SchemaDropdown (created by WrapperComponent)
          in WrapperComponent

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at fn (node_modules/@blueprintjs/popover2/node_modules/react-popper/lib/cjs/usePopper.js:58:9)
      at Object.forceUpdate (node_modules/@popperjs/core/src/createPopper.js:230:21)
      at node_modules/@popperjs/core/src/createPopper.js:240:22
```

How can I get rid of this?

**Comment by codeasashu** [comment]
Got it. I just needed to call `wrapper.update()` to let the state update and resolve all pending promises.

Here is the updated code:

```js
// __tests__/main.test.js

import React from 'react';
import {Popover2, Classes} from '@blueprintjs/popover2';
import {mount} from 'enzyme';
import {act} from '../../../test-utils';
import Main from "./main";

it('Responds to click', async () => {
    const clickHandler = jest.fn();
    const wrapper = mount(<Main handleOnClick={clickHandler} />);
    
    // Trigger a click
    const targetNode = wrapper.find(`.${Classes.POPOVER2_TARGET}`);
    await act(async () => {
        targetNode.simulate('click');
    });
    wrapper.update(); //Resolve all promises

    // Assert popup is opened
    expect(targetNode.getDOMNode()).toHaveClass(Classes.POPOVER2_OPEN);

    // Find the target
    wrapper.find(Popover2).find('.clickit').simulate('click');

    // Assert click is triggered
    expect(clickHandler).toHaveBeenCalled();
});
```
