### ISSUE TITLE
DateInput click causes popperInstance error - missing scheduleUpdate

### ISSUE THREAD

**Issue by dance-dance-banana-frenzy** [palantir/blueprint#5060]
#### Environment

- @blueprintjs/core: 3.51.3
- @blueprintjs/datetime: 3.23.18
- @blueprintjs/icons: 3.31.0
- @blueprintjs/popover2: 0.12.8
- @blueprintjs/select: 3.18.10
- react: 17.0.2
- react-dom: 17.0.2
- material-ui: 0.20.2 (rarely used - a dependency)
- npm: 6.14.11
- node: 14.15.5
- Google Chrome: Version 96.0.4664.93 (Official Build) (x86_64)
- macOS: Big Sur 11.6

I'm having some weird issues where I'm trying to replicate this on its own in a separate repo, but I'm only getting it to happen in the original project i'm working on. I've been working on upgrading everything to use Popover2 after upgrading react. It looks like the DateInput also uses the old popover and resizer components instead of Popover2/resizer2, and I suspect this is the cause for my problems until blueprint 4 is available. We also have a component that uses material-ui library that also uses popper - but that component and library is not yet loaded.

#### Steps to reproduce

```js
import React from 'react';
import PropTypes from 'prop-types';
import { DateInput } from '@blueprintjs/datetime';

const DateSelector = ({ value, onChange }) => {
  return <DateInput value={value} onChange={onChange} />;
};

DateSelector.propTypes = {
  onChange: PropTypes.func.isRequired,
  value: PropTypes.instanceOf(Date)
};

export default DateSelector;
```

1. Click inside date input box

#### Actual behavior
```
Uncaught TypeError: _this.popperInstance.scheduleUpdate is not a function
    at Popover.popperScheduleUpdate (Popper.js:128)
    at Object.Popover._this.reposition [as onResize] (popover.js:74)
    at ResizeObserver.<anonymous> (resizeSensor.js:29)
```
#### Steps to reproduce

1. Click anything to trigger a blur event

#### Actual behavior

```
Uncaught TypeError: _this.popperInstance.destroy is not a function
    at InnerPopper.destroyPopperInstance (Popper.js:110)
    at InnerPopper.componentWillUnmount (Popper.js:165)
    at callComponentWillUnmountWithTimer (react-dom.development.js:20413)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at safelyCallComponentWillUnmount (react-dom.development.js:20420)
    at commitUnmount (react-dom.development.js:20951)
    at unmountHostComponents (react-dom.development.js:21311)
    at commitDeletion (react-dom.development.js:21347)
```
then
```
The above error occurred in the <InnerPopper> component:

    at InnerPopper (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:13866:35)
    at Popper (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:14030:31)
    at Transition (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:157912:30)
    at CSSTransition (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:157356:35)
    at div
    at TransitionGroup (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:158458:30)
    at Portal (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:10700:47)
    at Overlay (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:9090:47)
    at span
    at Manager (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:13776:35)
    at Popover (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:9940:47)
    at DateInput (http://0.0.0.0:8080/vendors-node_modules_babel_runtime-corejs3_core-js-stable_instance_splice_js-node_modules_blu-7c741f.5b02bcc7a048223b52c1.js:793:28)
    at div
    at DateSelector (http://0.0.0.0:8080/Search.43b3bfa95704f65de09a.js:92:20)
    at div
    at O (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:167139:19741)
    at DateRangeFilter (http://0.0.0.0:8080/Search.43b3bfa95704f65de09a.js:36:74)
    at DateFilter (http://0.0.0.0:8080/Search.43b3bfa95704f65de09a.js:3129:82)
    at div
    at O (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:167139:19741)
    at Filters (http://0.0.0.0:8080/Search.43b3bfa95704f65de09a.js:3418:98)
    at div
    at O (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:167139:19741)
    at div
    at O (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:167139:19741)
    at Search (http://0.0.0.0:8080/Search.43b3bfa95704f65de09a.js:2789:74)
    at Routes (http://0.0.0.0:8080/vendors-node_modules_blueprintjs_core_lib_esm_accessibility_focusStyleManager_js-node_modules-31df01.522b3645b689387d9870.js:2990:5)
    at Suspense
    at PrimaryRoutes
    at div
    at div
    at AppShell (http://0.0.0.0:8080/App.2b50f14814ab6d9d8bb6.js:1010:74)
    at ScrollToTop (http://0.0.0.0:8080/App.2b50f14814ab6d9d8bb6.js:795:23)
    at Provider (http://0.0.0.0:8080/vendors-node_modules_blueprintjs_core_lib_esm_accessibility_focusStyleManager_js-node_modules-31df01.522b3645b689387d9870.js:397:20)
    at Router (http://0.0.0.0:8080/vendors-node_modules_blueprintjs_core_lib_esm_accessibility_focusStyleManager_js-node_modules-31df01.522b3645b689387d9870.js:2924:15)
    at BrowserRouter (http://0.0.0.0:8080/vendors-node_modules_blueprintjs_core_lib_esm_accessibility_focusStyleManager_js-node_modules-31df01.522b3645b689387d9870.js:2448:5)
    at App (http://0.0.0.0:8080/App.2b50f14814ab6d9d8bb6.js:953:20)
    at Suspense
    at ErrorBoundary (http://0.0.0.0:8080/main.295e85d0b0f10e394925.js?295e85d0b0f10e394925:22388:98)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```
and last
```
TypeError: _this.popperInstance.destroy is not a function
    at InnerPopper.destroyPopperInstance (Popper.js:110)
    at InnerPopper.componentWillUnmount (Popper.js:165)
    at callComponentWillUnmountWithTimer (react-dom.development.js:20413)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at safelyCallComponentWillUnmount (react-dom.development.js:20420)
    at commitUnmount (react-dom.development.js:20951)
    at unmountHostComponents (react-dom.development.js:21311)
    at commitDeletion (react-dom.development.js:21347)
```
#### Expected behavior

Input box on data input should have been focused

#### Possible solution

I'm at a loss. Is there a newer version that uses popover2 ?

I don't have a direct dependency on popper.js or react-popper, or @popperjs/core in my package.json file. I'm looking at package-lock.json and it seems various versions of popper are peppered through the dependency tree.

- @blueprintjs/core@3.51.3 requires popper.js@1.16.1 and react-popper@1.3.7, and has a dependency of react-popper@1.3.11 that depends on popper.js@1.14.4
- @blueprintjs/popover2 depends on @popperjs/core@2.5.4 and react-popper@2.2.4
- @material-ui/core@4.12.3 requires/depends on popper.js@1.16.1-lts
- @popperjs/core@2.11.0
- popper.js@1.16.1
- react-popper@2.2.5

**Comment by dance-dance-banana-frenzy** [comment]
Still scratching my head over this, but I have some updates. 

I'm testing with a bare-bones react/webpack app where my index.js file looks like
```js
import React from 'react';
import ReactDOM from 'react-dom';
import {DateInput} from '@blueprintjs/datetime';
const parseDate = () => {};
ReactDOM.render(<DateInput parseDate={parseDate} />, document.getElementById('root'));
```
I click inside the input box, and my console shows an error. After comparing webpack.config.js files between the actual project and bug test project, I found that this is related to anther problem during webpack build where I was originally get a warning from `Popper.js` and `popper.js` - both used by `react-popper`:
```
Compiled with problems:X

WARNING in ./node_modules/react-popper/lib/esm/Popper.js

There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /bug/node_modules/react-popper/lib/esm/Popper.js
    Used by 1 module(s), i. e.
    /bug/node_modules/react-popper/lib/esm/index.js
* /bug/node_modules/react-popper/lib/esm/popper.js
    Used by 2 module(s), i. e.
    /bug/node_modules/react-popper/lib/esm/Popper.js
```

My initial fix to this was to ignore warnings in 3rd party packages since I have no control over them. Here is the webpack config that I'm using:

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

module.exports = () =>  ({
  mode: 'development',
  devtool: 'source-map',
  entry: './src/index.js',
  ignoreWarnings: [/node_modules/], // lets me use the site without popper error
  resolve: {
    preferRelative: true, // This lets leaflet work, but breaks @blueprintjs/datetime DateInput
    extensions: ['.js']
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude:
          /node_modules\//,
        loader: 'babel-loader'
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin()
  ],
  devServer: {
    open: true
  }
});
```

Now, I'm also able to "fix" the bug in the Date Input component in a demo project if I change `preferRelative` to false. Yay! - but, this in turn causes a problem in another third party component unrelated to date input ...
```
ERROR in ../node_modules/leaflet/dist/leaflet.css (../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!../node_modules/leaflet/dist/leaflet.css) 5:36-81

Module not found: Error: Can't resolve 'images/layers.png' in '/big-proj/node_modules/leaflet/dist'
Did you mean './images/layers.png'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

I'm going to hunt down leaflet and see what's up, but is there a way to fix DateInput to use Popover2 instead?

**Comment by adidahiya** [comment]
@dance-dance-banana-frenzy In trying to migrate some code bases to Popover2, I realized that the components in the datetime & select packages (like DateInput) which still use Popover are a blocker for a smooth migration path. So, in the next month or so, I'm going to be adding "v2" versions of DateInput, Select, etc. which use Popover2 instead of Popover. Keep an eye out for those in the coming weeks after v4.0.0 stable is released...

**Comment by adidahiya** [comment]
DateInput2 fixes this problem, it uses Popover2.
