### ISSUE TITLE
`yarn verify` return an error

### ISSUE THREAD

**Issue by LoiKos** [palantir/blueprint#5379]
#### Environment

- Package version(s):
@blueprintjs/core 4.5.0
@blueprintjs/datetime 4.3.0
@blueprintjs/datetime2 0.1.0
@blueprintjs/popover2 1.4.0
@blueprintjs/select 4.4.0
- Operating System: macOS Monterey 12.4
- Browser name and version: Node 14

#### Steps to reproduce

1. Clone blueprint repo
1. run `yarn`
1. run `yarn verify`

#### Actual behavior

```sh
@blueprintjs/stylelint-plugin:     ✔ Warns when .bp3 is present (452ms)
@blueprintjs/stylelint-plugin:     ✔ Warns when .bp3 is present (CSS modules)
@blueprintjs/stylelint-plugin:     ✔ Warns when nested .bp3 is present even when not first selector
@blueprintjs/stylelint-plugin:     ✔ Warns when nested .bp3 is present even when not first selector (CSS modules)
@blueprintjs/stylelint-plugin:     ✔ Doesn't warn bp3 string is present but not as a prefix
@blueprintjs/stylelint-plugin:     ✔ Doesn't warn bp3 string is present but not as a prefix (CSS modules)
@blueprintjs/stylelint-plugin:     ✔ Doesn't warn when .bp3 is not present
@blueprintjs/stylelint-plugin:     ✔ Doesn't warn when .bp3 is not present (CSS modules)
@blueprintjs/stylelint-plugin:     ✔ Doesn't warn when .bp3 is present but lint rule is disabled
@blueprintjs/stylelint-plugin: /Users/loic/Code/blueprint/packages/stylelint-plugin/test/fixtures/no-prefix-literal/contains-bp3.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
@blueprintjs/stylelint-plugin:     ✔ Accepts a valid secondary config
@blueprintjs/stylelint-plugin: /Users/loic/Code/blueprint/packages/stylelint-plugin/test/fixtures/no-prefix-literal/contains-bp3.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
@blueprintjs/stylelint-plugin:     ✔ Rejects an invalid secondary config
@blueprintjs/stylelint-plugin:     ✔ Works for a double bp3 selector
@blueprintjs/stylelint-plugin:   checkImportExists
@blueprintjs/stylelint-plugin:     ✔ Returns false if no imports exist
@blueprintjs/stylelint-plugin:     ✔ Returns false if imports exist but not the one we want
@blueprintjs/stylelint-plugin:     ✔ Returns true if our import exists
@blueprintjs/stylelint-plugin:     ✔ Returns true if our import exists, and works with single quotes
packages/core/src/common/abstractPureComponent.ts@blueprintjs/stylelint-plugin:     ✔ Can match multiple paths
@blueprintjs/stylelint-plugin:     ✔ Handles less references
@blueprintjs/stylelint-plugin:   isHexColor
@blueprintjs/stylelint-plugin:     ✔ Accepts valid colors
@blueprintjs/stylelint-plugin:     ✔ Rejects invalid colors
@blueprintjs/stylelint-plugin:   normalizeHexColor
@blueprintjs/stylelint-plugin:     ✔ Uppercases hex colors
@blueprintjs/stylelint-plugin:     ✔ Converts three letter hexes into six letter hexes
@blueprintjs/stylelint-plugin:     ✔ Converts lowercase three letter hexes into uppercase six letter hexes
@blueprintjs/stylelint-plugin:   insertImport
@blueprintjs/stylelint-plugin:     ✔ Inserts an import at the top of the file when no imports are present
packages/core/src/common/abstractPureComponent2.ts@blueprintjs/stylelint-plugin:     ✔ Inserts an import below other imports
@blueprintjs/stylelint-plugin:     ✔ Inserts an import below the copyright header if no other imports exist
@blueprintjs/stylelint-plugin:     ✔ Inserts an import below other imports if the copyright header exists
@blueprintjs/stylelint-plugin:     ✔ Doesn't treat media queries as imports
@blueprintjs/stylelint-plugin:   30 passing (6s)
@blueprintjs/stylelint-plugin:   1 failing
@blueprintjs/stylelint-plugin:   1) no-color-literal
@blueprintjs/stylelint-plugin:        Warns when blueprint color literal is used (1):
@blueprintjs/stylelint-plugin:      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/loic/Code/blueprint/packages/stylelint-plugin/test/index.js)
@blueprintjs/stylelint-plugin:       at listOnTimeout (internal/timers.js:557:17)
@blueprintjs/stylelint-plugin:       at processTimers (internal/timers.js:500:7)
@blueprintjs/stylelint-plugin: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@blueprintjs/stylelint-plugin: error Command failed with exit code 1.
lerna ERR! yarn run test exited 1 in '@blueprintjs/stylelint-plugin'
lerna ERR! yarn run test stdout:
$ mocha test/index.js


  no-color-literal
    1) Warns when blueprint color literal is used (1)
    ✔ Warns when blueprint color literal is used (2)
    ✔ Doesn't warn when non-blueprint color literal is used

  no-prefix-literal
    ✔ Warns when .bp3 is present (452ms)
    ✔ Warns when .bp3 is present (CSS modules)
    ✔ Warns when nested .bp3 is present even when not first selector
    ✔ Warns when nested .bp3 is present even when not first selector (CSS modules)
    ✔ Doesn't warn bp3 string is present but not as a prefix
    ✔ Doesn't warn bp3 string is present but not as a prefix (CSS modules)
    ✔ Doesn't warn when .bp3 is not present
    ✔ Doesn't warn when .bp3 is not present (CSS modules)
    ✔ Doesn't warn when .bp3 is present but lint rule is disabled
    ✔ Accepts a valid secondary config
    ✔ Rejects an invalid secondary config
    ✔ Works for a double bp3 selector

  checkImportExists
    ✔ Returns false if no imports exist
    ✔ Returns false if imports exist but not the one we want
    ✔ Returns true if our import exists
    ✔ Returns true if our import exists, and works with single quotes
    ✔ Can match multiple paths
    ✔ Handles less references

  isHexColor
    ✔ Accepts valid colors
    ✔ Rejects invalid colors

  normalizeHexColor
    ✔ Uppercases hex colors
    ✔ Converts three letter hexes into six letter hexes
    ✔ Converts lowercase three letter hexes into uppercase six letter hexes

  insertImport
    ✔ Inserts an import at the top of the file when no imports are present
    ✔ Inserts an import below other imports
    ✔ Inserts an import below the copyright header if no other imports exist
    ✔ Inserts an import below other imports if the copyright header exists
    ✔ Doesn't treat media queries as imports


  30 passing (6s)
  1 failing

  1) no-color-literal
       Warns when blueprint color literal is used (1):
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/loic/Code/blueprint/packages/stylelint-plugin/test/index.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)



info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test stderr:
/Users/loic/Code/blueprint/packages/stylelint-plugin/test/fixtures/no-prefix-literal/contains-bp3.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
/Users/loic/Code/blueprint/packages/stylelint-plugin/test/fixtures/no-prefix-literal/contains-bp3.scss: When linting something other than CSS, you should install an appropriate syntax, e.g. "postcss-scss", and use the "customSyntax" option
error Command failed with exit code 1.
lerna ERR! yarn run test exited 1 in '@blueprintjs/stylelint-plugin'
lerna WARN complete Waiting for 9 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
packages/core/src/common/classes.tsERROR: "test" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Expected behavior

`yarn verify` run without errors 

### Additional 

Work fine when running test under `/packages/stylelint-plugin` with `yarn test`

**Comment by adidahiya** [comment]
1. can you try with the Node 16 version recommended in our `.nvmrc` file?
2. is this error consistently reproducible? it looks like a testing timeout which can vary from machine to machine depending on available resources.
3. it's usually best to run `yarn test` or `yarn lint` or `yarn verify` in each individual package, rather than at the root. I recommend doing this for any non-beginner developer hoping to contribute to Blueprint.

**Comment by LoiKos** [comment]
i'll retry with a fresh install and node@16 when i get some times. During my tests i reproduce it consistently bug i only test with one machine. So maybe it's related to my machine. 

Ok for 3. that what i do at the end but i start by follow the Contribution Guide that said to run `yarn verify`. I get no error with command in individual package.

**Comment by adidahiya** [comment]
Ok, I've updated the [Development practices wiki page](https://github.com/palantir/blueprint/wiki/Development-practices) to reflect my advice.
