### ISSUE TITLE
Postinstall scripts fail expecting `python` to be on the path

### ISSUE THREAD

**Issue by gluxon** [palantir/blueprint#5422]
#### Environment

- __Package version(s)__: Develop commit bf4c8bead
- __Operating System__: macOS 12.4
- __Browser name and version__: N/A

#### Steps to reproduce

```
❯ git clone git@github.com:palantir/blueprint
❯ cd blueprint
❯ yarn
```

```
❯ node --version
v14.19.3

/Volumes/git/blueprint develop * 
❯ yarn --version
1.22.19
```

#### Actual behavior

Here's the relevant section of the `yarn` log. It looks like `node-gyp@7.1.2` is trying to execute `python` on the path, [which no longer exists for macOS Monterey](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python).

```
[5/5] 🔨  Building fresh packages...
[8/9] ⠂ oniguruma
[2/9] ⠂ ttf2woff2
[-/9] ⠂ waiting...
[-/9] ⠂ waiting...
error /Volumes/git/blueprint/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Volumes/git/blueprint/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@14.19.3 | darwin | x64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/git/blueprint/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bcheng/Library/Caches/node-gyp/14.19.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bcheng/Library/Caches/node-gyp/14.19.3',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bcheng/Library/Caches/node-gyp/14.19.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/git/blueprint/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
env: python: No such file or directory
make: *** [Release/oniguruma.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/usr/local/Cellar/node@14/14.19.3/bin/node" "/Volumes/git/blueprint/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/git/blueprint/node_modules/oniguruma
```

#### Possible solution

`node-gyp@8.0.0` fixes the issue above by removing Python 2 support entirely: https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md#v800-2021-04-03

It looks like `@npmcli/run-script` pulls in an older version of `node-gyp@7.1.2` that relies on `python` being on the path.

The current dependency pathing is:

- `@lerna/add@4.0.0` -> `pacote@11.3.5` -> `@npmcli/run-script@1.8.6` -> `node-gyp@7.1.2`

`@npmcli/run-script@2.0.0` bumped its `node-gyp` dependency to a working version, but since the dependency chain goes all the way back to lerna, I think upgrading to lerna 5 is necessary to fix this build issue.

We could add `node-gyp@8.x` to Blueprint's root `devDependencies`, or better control which version of `node-gyp` is chosen to hoist.

**Comment by adidahiya** [comment]
Can you try building with Node 16, as specified in `.nvmrc`? I know the README and package.json version constraint says otherwise, but this may fix your problem.

**Comment by gluxon** [comment]
Thanks for the suggestion. Just gave that a shot:

```
/Volumes/git/blueprint develop 
❯ node --version                                            
v16.16.0

/Volumes/git/blueprint develop 
❯ git clean -fdX                             
Removing node_modules/
Removing packages/colors/node_modules/
Removing packages/core/node_modules/
Removing packages/datetime/node_modules/
Removing packages/datetime2/node_modules/
Removing packages/demo-app/node_modules/
Removing packages/docs-app/node_modules/
Removing packages/docs-data/node_modules/
Removing packages/docs-theme/node_modules/
Removing packages/eslint-config/node_modules/
Removing packages/eslint-plugin/node_modules/
Removing packages/icons/node_modules/
Removing packages/karma-build-scripts/node_modules/
Removing packages/landing-app/node_modules/
Removing packages/node-build-scripts/node_modules/
Removing packages/popover2/node_modules/
Removing packages/select/node_modules/
Removing packages/stylelint-plugin/node_modules/
Removing packages/table-dev-app/node_modules/
Removing packages/table/node_modules/
Removing packages/test-commons/node_modules/
Removing packages/timezone/node_modules/
Removing packages/tslint-config/node_modules/
Removing packages/webpack-build-scripts/node_modules/
direnv: loading /Volumes/git/blueprint/.envrc                                                                        
direnv: export ~PATH

/Volumes/git/blueprint develop 8s214ms 
❯ yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
warning better-handlebars@0.1.1: The engine "atom" appears to be invalid.
warning language-less@0.34.3: The engine "atom" appears to be invalid.
[4/5] 🔗  Linking dependencies...
warning " > stylelint-config-palantir@6.0.1" has unmet peer dependency "stylelint@^14.2.0".
warning "stylelint-config-palantir > stylelint-config-standard@24.0.0" has unmet peer dependency "stylelint@^14.0.0".
warning "stylelint-config-palantir > stylelint-order@5.0.0" has unmet peer dependency "stylelint@^14.0.0".
warning " > stylelint-scss@4.2.0" has unmet peer dependency "stylelint@^14.5.1".
warning "stylelint-config-palantir > stylelint-config-standard > stylelint-config-recommended@6.0.0" has unmet peer dependency "stylelint@^14.0.0".
warning " > @blueprintjs/core@4.6.0" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/core@4.6.0" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/datetime@4.3.2" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/datetime@4.3.2" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/datetime2@0.3.0" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/datetime2@0.3.0" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/docs-theme@4.3.2" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/docs-theme@4.3.2" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/popover2@1.4.2" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/popover2@1.4.2" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/select@4.4.2" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/select@4.4.2" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/stylelint-plugin@2.0.8" has unmet peer dependency "stylelint@^14.6.1".
warning " > @blueprintjs/table@4.3.2" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/table@4.3.2" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/test-commons@1.0.9" has unmet peer dependency "react@>=15.3.0".
warning " > @blueprintjs/timezone@4.4.1" has unmet peer dependency "react@^16.8 || 17 || 18".
warning " > @blueprintjs/timezone@4.4.1" has unmet peer dependency "react-dom@^16.8 || 17 || 18".
warning " > @blueprintjs/tslint-config@3.3.1" has unmet peer dependency "tslint@^6.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/core > @vgrid/sass-inline-svg@1.0.1" has unmet peer dependency "sass@^1.28.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/core > webpack-cli@3.3.12" has unmet peer dependency "webpack@4.x.x".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/demo-app > copy-webpack-plugin@6.4.0" has unmet peer dependency "webpack@^4.37.0 || ^5.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/demo-app > webpack-dev-server@3.11.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/eslint-config > @typescript-eslint/eslint-plugin-tslint@5.21.0" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/karma-build-scripts > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/karma-build-scripts > karma-webpack@5.0.0" has unmet peer dependency "webpack@^5.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/node-build-scripts > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/popover2 > sass-inline-svg@1.2.3" has unmet peer dependency "node-sass@^4.5.3".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.2" has incorrect peer dependency "react@^15.5.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.2" has unmet peer dependency "react-dom@^15.5.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/test-commons > enzyme-adapter-react-15@1.4.2" has unmet peer dependency "react-test-renderer@^15.5.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/test-commons > enzyme-adapter-react-16@1.15.5" has unmet peer dependency "react-dom@^16.0.0-0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/demo-app > webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependency "webpack@^4.0.0".
warning "workspace-aggregator-59936d11-d559-459f-bdbd-d53c6dc67690 > @blueprintjs/docs-data > @documentalist/compiler > typedoc@0.19.2" has incorrect peer dependency "typescript@3.9.x || 4.0.x".
[5/5] 🔨  Building fresh packages...
[-/9] ⠐ waiting...
[2/9] ⠐ ttf2woff2
[8/9] ⠐ oniguruma
[-/9] ⠐ waiting...
error /Volumes/git/blueprint/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Volumes/git/blueprint/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.16.0 | darwin | x64
gyp info find Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.16.0/node-v16.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.16.0/SHASUMS256.txt
(node:3348) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/git/blueprint/node_modules/oniguruma/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/bcheng/Library/Caches/node-gyp/16.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/bcheng/Library/Caches/node-gyp/16.16.0',
gyp info spawn args   '-Dnode_gyp_dir=/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/bcheng/Library/Caches/node-gyp/16.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Volumes/git/blueprint/node_modules/oniguruma',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
env: python: No such file or directory
make: *** [Release/oniguruma.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Volumes/git/blueprint/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.5.0
gyp ERR! command "/usr/local/Cellar/node@16/16.16.0/bin/node" "/Volumes/git/blueprint/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Volumes/git/blueprint/node_modules/oniguruma
```

**Comment by gluxon** [comment]
I think it's the version of `node-gyp` that gets linked to `node_modules/.bin/node-gyp`. Based on `node-gyp`'s changelog, I think we have to bump past `node-gyp` 8.x.

```
/Volumes/git/blueprint develop 
❯ readlink node_modules/.bin/node-gyp                                                
../@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js

/Volumes/git/blueprint develop 
❯ jq '.version' < node_modules/@npmcli/run-script/node_modules/node-gyp/package.json
"7.1.2"
```

I took a shot at upgrading to Lerna 5.x and it did seem to resolve this issue. Would you take a PR upgrading to lerna 5.x?

**Comment by ZeRego** [comment]
I can confirm that changing to `"lerna": "^5.1.8",` fixed this error when installing dependencies but got some failing tests when running `yarn verify`.

```
10 07 2022 09:30:18.405:INFO [Chrome Headless 103.0.5060.114 (Mac OS 10.15.7)]: Connected on socket sYWp7lUO6mbyF3t0AAAB with id 37565624
     _________________________________________________
 👌   ooooooooooooooooooooooooooooooooooXXXXXXXXXXXXX-- 
     ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

 convertLocalDateToTimezoneTime
    Returns the same date when current time is the same as passed
       1) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200826:86)

    Returns a date converted to the local timezone passed through adapting for daylight savings
       2) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200838:90)

    Returns a date converted to the local timezone passed through adapting for daylight savings 2
       3) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200850:90)

    Returns a date that might be equal to the current time, but not during daylight savings
       4) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200860:90)


 convertDateToLocalEquivalentOfTimezoneTime
    Returns the same date when current time is the same as passed
       5) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200866:86)

    Returns a date converted to the local timezone passed through adapting for daylight savings
       6) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200878:90)

    Returns a date converted to the local timezone passed through adapting for daylight savings 2
       7) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200890:90)

    Returns a date that might be equal to the current time, but not during daylight savings
       8) AssertionError: expected false to equal true
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:200900:90)


 <TimezoneSelect>
    if query is empty, shows initial items
       9) AssertionError: expected [ Array(33) ] to deeply equal [ Array(34) ]
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:201106:23)

    if showLocalTimezone=true, the local timezone is rendered at the top of the item list
       10) AssertionError: expected 'Europe/London' to equal 'Etc/UTC'
          at Context.<anonymous> (/var/folders/vk/cw16qf815q92_xg52ng1twm00000gn/T/_karma_webpack_72428/commons.js:201128:23)


 LOG MESSAGES FOR: Chrome Headless 103.0.5060.114 (Mac OS 10.15.7) INSTANCE #: 37565624
    '%cDownload the React DevTools for a better development experience: https://fb.me/react-devtools', 'font-weight:bold'
    'Enzyme configured with *ReactSixteenAdapter*'

   26 passed   10 failed   1 skipped

⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈⠈
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test stderr:
error Command failed with exit code 1.
ERROR: "test:karma" exited with 1.
error Command failed with exit code 1.
lerna ERR! yarn run test exited 1 in '@blueprintjs/datetime2'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by adidahiya** [comment]
Can you see if my upgrades in #5427 fixed the issue?

**Comment by gluxon** [comment]
Thank you @adidahiya. That indeed fixed `yarn` for me. I cleared `node_modules` to be sure.
