### ISSUE TITLE
Error building `colors` and `icons` on Windows

### ISSUE THREAD

**Issue by ItsHarper** [palantir/blueprint#6068]
#### Environment

- __Package version(s)__: Development environment at ef216076dd59d39bd047f5224f35a1fb980e964c
- __Operating System__: Windows 11
- __Browser name and version__: n/a

#### Code Sandbox

n/a

#### Steps to reproduce

1. Make a fresh clone of the blueprint git repository
2. Run `yarn`
3. Run `cd packages\colors`
4. Run `yarn compile`
5. Run `yarn lint`

#### Actual behavior

The following error was printed
```
Error: Could not find "@blueprintjs/stylelint-plugin". Do you need a `configBasedir`?
    at configurationError (C:\Users\Noah\blueprint\node_modules\stylelint\lib\utils\configurationError.js:11:49)
    at getModulePath (C:\Users\Noah\blueprint\node_modules\stylelint\lib\utils\getModulePath.js:28:9)
    at C:\Users\Noah\blueprint\node_modules\stylelint\lib\augmentConfig.js:155:12
    at Array.map (<anonymous>)
    at absolutizePaths (C:\Users\Noah\blueprint\node_modules\stylelint\lib\augmentConfig.js:153:44)
    at augmentConfigBasic (C:\Users\Noah\blueprint\node_modules\stylelint\lib\augmentConfig.js:62:9)
    at async augmentConfigFull (C:\Users\Noah\blueprint\node_modules\stylelint\lib\augmentConfig.js:106:24)
    at async runLoad (C:\Users\Noah\blueprint\node_modules\cosmiconfig\dist\Explorer.js:104:31)
    at async cacheWrapper (C:\Users\Noah\blueprint\node_modules\cosmiconfig\dist\cacheWrapper.js:16:18)
    at async getConfigForFile (C:\Users\Noah\blueprint\node_modules\stylelint\lib\getConfigForFile.js:56:5) {
  code: 78
}
error Command failed with exit code 2.
```

#### Expected behavior
The command to finish successfully

**Comment by ItsHarper** [comment]
This also applies to the `icons` package

**Comment by ItsHarper** [comment]
Running `yarn compile` and `yarn lint` on the `stylelint-plugin` package fixes that specific error, but I'm having other build issues.

When I run `yarn compile` from the root, it says that the `@blueprintjs/icons:compile` and `@blueprintjs/colors:compile` targets failed. However, once I fixed the `stylelint-plugin` error, running `yarn compile` and `yarn lint` on those packages succeeds. 

After running `yarn compile` from the root, the `packages/colors/yarn-error.log` file includes the following contents (minus the npm manifest):
```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\bin\yarn.js run compile:css-colors

PATH:  <redacted>

Yarn version: 
  1.22.19

Node version: 
  18.15.0

Platform: 
  win32 x64

Trace: 
  TypeError: Cannot create property 'users-noah-appdata-roaming-npm-node-modules-node-gyp-bin-node-gyp-js' on string '{"users-noah-appdata-roaming-npm-node-modules-node-gyp-bin-node-gyp-js":""}'
      at set (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:53951:28)
      at set (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:53965:14)
      at set (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:53945:16)
      at objectPath.set (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:53998:14)
      at NpmRegistry.mergeEnv (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:92160:18)
      at NpmRegistry.<anonymous> (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:31950:12)
      at Generator.next (<anonymous>)
      at step (C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:310:30)
      at C:\Users\Noah\AppData\Roaming\nvm\v18.15.0\node_modules\yarn\lib\cli.js:328:14
      at new Promise (<anonymous>)
```

Interestingly, running `yarn verify` from the `colors` directory results in an (almost?) identical `yarn-error.log` file. Only running `yarn compile` and `yarn lint` separately works.

**Comment by ItsHarper** [comment]
I'll leave this open, but WSL is an acceptable workaround for now.

**Comment by adidahiya** [comment]
I'm aware there are some issues running our build tooling on Windows, see https://github.com/palantir/blueprint/issues/4221. It hasn't been a priority to fix them since most Blueprint users use macOS or Linux. Good to know that WSL is an acceptable workaround.
