### ISSUE TITLE
Hotkey navigation on blueprintjs.com/docs sometimes makes the page crash

### ISSUE THREAD

**Issue by michaeledryan** [palantir/blueprint#6381]
#### Environment

https://blueprintjs.com/docs/
Chrome 116.0.5845.179
Mac OS X

#### Steps to reproduce

1. Navigate to https://blueprintjs.com/docs/#core/components/breadcrumbs
1. Click somewhere in the page body. Press `[`.

#### Actual behavior

The URL changes to https://blueprintjs.com/docs/#core/components, and the page goes blank. Errors are reported in the console:

```
Uncaught TypeError: Cannot read properties of null (reading 'offsetTop')
    at t.maybeScrollToActivePageMenuItem (docs-app.js:1:5894972)
    at t.componentDidUpdate (docs-app.js:1:5894075)
    at dr (docs-app.js:1:990333)
    at Ll (docs-app.js:1:1007962)
    at t.unstable_runWithPriority (docs-app.js:1:1035731)
    at Ks (docs-app.js:1:951919)
    at Nl (docs-app.js:1:1004621)
    at bl (docs-app.js:1:1000768)
    at docs-app.js:1:952210
    at t.unstable_runWithPriority (docs-app.js:1:1035731)
```

Refreshing and using the browser back button does not get you out of the blank page.

#### Expected behavior

Navigation is either prevented between certain subdivisions or skips the headers instead of crashing the page.

**Comment by adidahiya** [comment]
thanks for the bug report, I can repro this issue
