### ISSUE TITLE
Allow for sequencing hotkeys

### ISSUE THREAD

**Issue by waltonseymour** [palantir/blueprint#811]
Would be a useful feature to have hotkey sequences in addition to combos.
Ex: `dd` in vim to delete.

**Comment by giladgray** [comment]
great idea but low priority for the team. would happily accept contributions though.

**Comment by chrisramakers** [comment]
This would indeed be a nice addition, I love the clean implementation of HotKeys right now, sequencing would be a welcome addition. I feel that sequencing in web apps feels more natural than modifier keys, using modifier keys always gives me the feeling i'm invoking functionality from my browser, not the webapp i'm using. For webapps key sequences (shift > shift for search for example) feels more natural.

**Comment by giladgray** [comment]
@chrisramakers any interest in building this feature out? it's not a priority for the team so we're going to have to rely on contributions for this in the short term.

**Comment by chrisramakers** [comment]
@giladgray I'd love to but I'd be diving head first into unknown territory,  I've got enough experience programming but i'm only just exploring react and es6/typescript ... but this might be a good opportunity to learn ... are there and guidelines on developing for blueprint?

**Comment by shounak7** [comment]
Hey @giladgray could I take this on? I think within a week or two I should be able to provide you with an update on my progress or let you know if I think that I can't handle it.

**Comment by shounak7** [comment]
never mind, figured it out. had to run $ sudo apt-get install build-essential

**Comment by shounak7** [comment]
alright, new issue on the yarn verify now. any advice?

`
shounak@shounak:~/blueprint$ yarn verify
yarn run v1.10.1
$ npm-run-all -s compile dist:libs dist:apps -p test lint
$ lerna run compile
lerna info version 2.11.0
lerna info versioning independent
$ tsc -p ./src
lerna ERR! compile Errored while running script in '@blueprintjs/tslint-config'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run compile
lerna ERR! error Command failed with exit code 2.
lerna ERR! $ tsc -p ./src
lerna ERR! ../../node_modules/tsutils/typeguard/2.9/node.d.ts:3:69 - error TS2694: Namespace 'ts' has no exported member 'ImportTypeNode'.
lerna ERR! 
lerna ERR! 3 export declare function isImportTypeNode(node: ts.Node): node is ts.ImportTypeNode;
lerna ERR!                                                                       ~~~~~~~~~~~~~~
lerna ERR! 
lerna ERR! 
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/home/shounak/blueprint/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: yarn run compile
error Command failed with exit code 2.
$ tsc -p ./src
../../node_modules/tsutils/typeguard/2.9/node.d.ts:3:69 - error TS2694: Namespace 'ts' has no exported member 'ImportTypeNode'.

3 export declare function isImportTypeNode(node: ts.Node): node is ts.ImportTypeNode;
                                                                      ~~~~~~~~~~~~~~


info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/home/shounak/blueprint/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  code: 1,
  killed: false,
  stdout: '$ tsc -p ./src\n\u001b[96m../../node_modules/tsutils/typeguard/2.9/node.d.ts\u001b[0m:\u001b[93m3\u001b[0m:\u001b[93m69\u001b[0m - \u001b[91merror\u001b[0m\u001b[90m TS2694: \u001b[0mNamespace \'ts\' has no exported member \'ImportTypeNode\'.\n\n\u001b[30;47m3\u001b[0m export declare function isImportTypeNode(node: ts.Node): node is ts.ImportTypeNode;\n\u001b[30;47m \u001b[0m \u001b[91m                                                                    ~~~~~~~~~~~~~~\u001b[0m\n\n\ninfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 2.\n',
  failed: true,
  signal: null,
  cmd: 'yarn run compile',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "compile" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by shounak7** [comment]
hey @giladgray let me know if you know anything about the above error

**Comment by shounak7** [comment]
Hey, just a heads up, I'm not planning on working on this anymore

**Comment by giladgray** [comment]
i think i fixed that error in #3078, if you want to try updating to latest `develop`.
